-- ================================================================
-- reset-and-seed.sql
-- Execute UMA VEZ no Supabase Dashboard → SQL Editor
-- antes de correr o comando de importação.
-- 
-- O que faz:
--   1. Limpa TODOS os dados LC131 (TRUNCATE rápido)
--   2. Desactiva RLS em tab_drs e tab_rras
--   3. Insere os 645 municípios em tab_drs e tab_rras
-- ================================================================

-- ── 1. Limpar tabela LC131 (TRUNCATE é muito mais rápido que DELETE) ──
TRUNCATE TABLE public.lc131_despesas RESTART IDENTITY;

-- ── 2 + 3. DRS/RRAS seed (desactiva RLS + insere municípios) ─────────
-- ================================================================
-- seed-drs-rras.sql
-- Gerado automaticamente por scripts/gen-drs-rras-seed.cjs
-- Execute no Supabase Dashboard â†’ SQL Editor
-- ================================================================

-- Corrige o RLS das tabelas de referÃªncia (permite escrita)
ALTER TABLE public.tab_drs  DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tab_rras DISABLE ROW LEVEL SECURITY;

-- DÃ¡ acesso pÃºblico de leitura sem RLS (GRANT jÃ¡ garante isso)
GRANT SELECT ON public.tab_drs  TO anon, authenticated;
GRANT SELECT ON public.tab_rras TO anon, authenticated;

-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tab_drs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO public.tab_drs (municipio, drs) VALUES
  ('ADAMANTINA', '09 MarÃ­lia'),
  ('ADOLFO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('AGUAI', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('AGUAS DA PRATA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('AGUAS DE LINDOIA', '07 Campinas'),
  ('AGUAS DE SANTA BARBARA', '06 Bauru'),
  ('AGUAS DE SAO PEDRO', '10 Piracicaba'),
  ('AGUDOS', '06 Bauru'),
  ('ALAMBARI', '16 Sorocaba'),
  ('ALFREDO MARCONDES', '11 Presidente Prudente'),
  ('ALTAIR', '05 Barretos'),
  ('ALTINOPOLIS', '13 RibeirÃ£o Preto'),
  ('ALTO ALEGRE', '02 AraÃ§atuba'),
  ('ALUMINIO', '16 Sorocaba'),
  ('ALVARES FLORENCE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ALVARES MACHADO', '11 Presidente Prudente'),
  ('ALVARO DE CARVALHO', '09 MarÃ­lia'),
  ('ALVINLANDIA', '09 MarÃ­lia'),
  ('AMERICANA', '07 Campinas'),
  ('AMERICO BRASILIENSE', '03 Araraquara'),
  ('AMERICO DE CAMPOS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('AMPARO', '07 Campinas'),
  ('ANALANDIA', '10 Piracicaba'),
  ('ANDRADINA', '02 AraÃ§atuba'),
  ('ANGATUBA', '16 Sorocaba'),
  ('ANHEMBI', '06 Bauru'),
  ('ANHUMAS', '11 Presidente Prudente'),
  ('APARECIDA', '17 TaubatÃ©'),
  ('APARECIDA D''OESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('APIAI', '16 Sorocaba'),
  ('ARACARIGUAMA', '16 Sorocaba'),
  ('ARACATUBA', '02 AraÃ§atuba'),
  ('ARACOIABA DA SERRA', '16 Sorocaba'),
  ('ARAMINA', '08 Franca'),
  ('ARANDU', '06 Bauru'),
  ('ARAPEI', '17 TaubatÃ©'),
  ('ARARAQUARA', '03 Araraquara'),
  ('ARARAS', '10 Piracicaba'),
  ('ARCO IRIS', '09 MarÃ­lia'),
  ('AREALVA', '06 Bauru'),
  ('AREIAS', '17 TaubatÃ©'),
  ('AREIOPOLIS', '06 Bauru'),
  ('ARIRANHA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ARTUR NOGUEIRA', '07 Campinas'),
  ('ARUJA', '01 Grande SÃ£o Paulo'),
  ('ASPASIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ASSIS', '09 MarÃ­lia'),
  ('ATIBAIA', '07 Campinas'),
  ('AURIFLAMA', '02 AraÃ§atuba'),
  ('AVAI', '06 Bauru'),
  ('AVANHANDAVA', '02 AraÃ§atuba'),
  ('AVARE', '06 Bauru'),
  ('BADY BASSIT', '15 SÃ£o JosÃ© do Rio Preto'),
  ('BALBINOS', '06 Bauru'),
  ('BALSAMO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('BANANAL', '17 TaubatÃ©'),
  ('BARAO DE ANTONINA', '06 Bauru'),
  ('BARBOSA', '02 AraÃ§atuba'),
  ('BARIRI', '06 Bauru'),
  ('BARRA BONITA', '06 Bauru'),
  ('BARRA DO CHAPEU', '16 Sorocaba'),
  ('BARRA DO TURVO', '12 Registro'),
  ('BARRETOS', '05 Barretos'),
  ('BARRINHA', '13 RibeirÃ£o Preto'),
  ('BARUERI', '01 Grande SÃ£o Paulo'),
  ('BASTOS', '09 MarÃ­lia'),
  ('BATATAIS', '13 RibeirÃ£o Preto'),
  ('BAURU', '06 Bauru'),
  ('BEBEDOURO', '05 Barretos'),
  ('BENTO DE ABREU', '02 AraÃ§atuba'),
  ('BERNARDINO DE CAMPOS', '09 MarÃ­lia'),
  ('BERTIOGA', '04 Baixada Santista'),
  ('BILAC', '02 AraÃ§atuba'),
  ('BIRIGUI', '02 AraÃ§atuba'),
  ('BIRITIBA-MIRIM', '01 Grande SÃ£o Paulo'),
  ('BOA ESPERANCA DO SUL', '03 Araraquara'),
  ('BOCAINA', '06 Bauru'),
  ('BOFETE', '06 Bauru'),
  ('BOITUVA', '16 Sorocaba'),
  ('BOM JESUS DOS PERDOES', '07 Campinas'),
  ('BOM SUCESSO DE ITARARE', '16 Sorocaba'),
  ('BORA', '09 MarÃ­lia'),
  ('BORACEIA', '06 Bauru'),
  ('BORBOREMA', '03 Araraquara'),
  ('BOREBI', '06 Bauru'),
  ('BOTUCATU', '06 Bauru'),
  ('BRAGANCA PAULISTA', '07 Campinas'),
  ('BRAUNA', '02 AraÃ§atuba'),
  ('BREJO ALEGRE', '02 AraÃ§atuba'),
  ('BRODOWSKI', '13 RibeirÃ£o Preto'),
  ('BROTAS', '06 Bauru'),
  ('BURI', '16 Sorocaba'),
  ('BURITAMA', '02 AraÃ§atuba'),
  ('BURITIZAL', '08 Franca'),
  ('CABRALIA PAULISTA', '06 Bauru'),
  ('CABREUVA', '07 Campinas'),
  ('CACAPAVA', '17 TaubatÃ©'),
  ('CACHOEIRA PAULISTA', '17 TaubatÃ©'),
  ('CACONDE', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('CAFELANDIA', '06 Bauru'),
  ('CAIABU', '11 Presidente Prudente'),
  ('CAIEIRAS', '01 Grande SÃ£o Paulo'),
  ('CAIUA', '11 Presidente Prudente'),
  ('CAJAMAR', '01 Grande SÃ£o Paulo'),
  ('CAJATI', '12 Registro'),
  ('CAJOBI', '05 Barretos'),
  ('CAJURU', '13 RibeirÃ£o Preto'),
  ('CAMPINA DO MONTE ALEGRE', '16 Sorocaba'),
  ('CAMPINAS', '07 Campinas'),
  ('CAMPO LIMPO PAULISTA', '07 Campinas'),
  ('CAMPOS DO JORDAO', '17 TaubatÃ©'),
  ('CAMPOS NOVOS PAULISTA', '09 MarÃ­lia'),
  ('CANANEIA', '12 Registro'),
  ('CANAS', '17 TaubatÃ©'),
  ('CANDIDO MOTA', '09 MarÃ­lia'),
  ('CANDIDO RODRIGUES', '03 Araraquara'),
  ('CANITAR', '09 MarÃ­lia'),
  ('CAPAO BONITO', '16 Sorocaba'),
  ('CAPELA DO ALTO', '16 Sorocaba'),
  ('CAPIVARI', '10 Piracicaba'),
  ('CARAGUATATUBA', '17 TaubatÃ©'),
  ('CARAPICUIBA', '01 Grande SÃ£o Paulo'),
  ('CARDOSO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('CASA BRANCA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('CASSIA DOS COQUEIROS', '13 RibeirÃ£o Preto'),
  ('CASTILHO', '02 AraÃ§atuba'),
  ('CATANDUVA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('CATIGUA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('CEDRAL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('CERQUEIRA CESAR', '06 Bauru'),
  ('CERQUILHO', '16 Sorocaba'),
  ('CESARIO LANGE', '16 Sorocaba'),
  ('CHARQUEADA', '10 Piracicaba'),
  ('CHAVANTES', '09 MarÃ­lia'),
  ('CLEMENTINA', '02 AraÃ§atuba'),
  ('COLINA', '05 Barretos'),
  ('COLOMBIA', '05 Barretos'),
  ('CONCHAL', '10 Piracicaba'),
  ('CONCHAS', '06 Bauru'),
  ('CORDEIROPOLIS', '10 Piracicaba'),
  ('COROADOS', '02 AraÃ§atuba'),
  ('CORONEL MACEDO', '06 Bauru'),
  ('CORUMBATAI', '10 Piracicaba'),
  ('COSMOPOLIS', '07 Campinas'),
  ('COSMORAMA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('COTIA', '01 Grande SÃ£o Paulo'),
  ('CRAVINHOS', '13 RibeirÃ£o Preto'),
  ('CRISTAIS PAULISTA', '08 Franca'),
  ('CRUZALIA', '09 MarÃ­lia'),
  ('CRUZEIRO', '17 TaubatÃ©'),
  ('CUBATAO', '04 Baixada Santista'),
  ('CUNHA', '17 TaubatÃ©'),
  ('DESCALVADO', '03 Araraquara'),
  ('DIADEMA', '01 Grande SÃ£o Paulo'),
  ('DIRCE REIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('DIVINOLANDIA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('DOBRADA', '03 Araraquara'),
  ('DOIS CORREGOS', '06 Bauru'),
  ('DOLCINOPOLIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('DOURADO', '03 Araraquara'),
  ('DRACENA', '11 Presidente Prudente'),
  ('DUARTINA', '06 Bauru'),
  ('DUMONT', '13 RibeirÃ£o Preto'),
  ('ECHAPORA', '09 MarÃ­lia'),
  ('ELDORADO', '12 Registro'),
  ('ELIAS FAUSTO', '10 Piracicaba'),
  ('ELISIARIO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('EMBAUBA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('EMBU', '01 Grande SÃ£o Paulo'),
  ('EMBU-GUACU', '01 Grande SÃ£o Paulo'),
  ('EMILIANOPOLIS', '11 Presidente Prudente'),
  ('ENGENHEIRO COELHO', '10 Piracicaba'),
  ('ESPIRITO SANTO DO PINHAL', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('ESPIRITO SANTO DO TURVO', '09 MarÃ­lia'),
  ('ESTIVA GERBI', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('ESTRELA DO NORTE', '11 Presidente Prudente'),
  ('ESTRELA D''OESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('EUCLIDES DA CUNHA PAULISTA', '11 Presidente Prudente'),
  ('FARTURA', '06 Bauru'),
  ('FERNANDO PRESTES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('FERNANDOPOLIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('FERNAO', '09 MarÃ­lia'),
  ('FERRAZ DE VASCONCELOS', '01 Grande SÃ£o Paulo'),
  ('FLORA RICA', '11 Presidente Prudente'),
  ('FLOREAL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('FLORIDA PAULISTA', '09 MarÃ­lia'),
  ('FLORINIA', '09 MarÃ­lia'),
  ('FRANCA', '08 Franca'),
  ('FRANCISCO MORATO', '01 Grande SÃ£o Paulo'),
  ('FRANCO DA ROCHA', '01 Grande SÃ£o Paulo'),
  ('GABRIEL MONTEIRO', '02 AraÃ§atuba'),
  ('GALIA', '09 MarÃ­lia'),
  ('GARCA', '09 MarÃ­lia'),
  ('GASTAO VIDIGAL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('GAVIAO PEIXOTO', '03 Araraquara'),
  ('GENERAL SALGADO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('GETULINA', '06 Bauru'),
  ('GLICERIO', '02 AraÃ§atuba'),
  ('GUAICARA', '06 Bauru'),
  ('GUAIMBE', '09 MarÃ­lia'),
  ('GUAIRA', '05 Barretos'),
  ('GUAPIACU', '15 SÃ£o JosÃ© do Rio Preto'),
  ('GUAPIARA', '16 Sorocaba'),
  ('GUARA', '08 Franca'),
  ('GUARACAI', '02 AraÃ§atuba'),
  ('GUARACI', '05 Barretos'),
  ('GUARANI D''OESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('GUARANTA', '09 MarÃ­lia'),
  ('GUARARAPES', '02 AraÃ§atuba'),
  ('GUARAREMA', '01 Grande SÃ£o Paulo'),
  ('GUARATINGUETA', '17 TaubatÃ©'),
  ('GUAREI', '16 Sorocaba'),
  ('GUARIBA', '13 RibeirÃ£o Preto'),
  ('GUARUJA', '04 Baixada Santista'),
  ('GUARULHOS', '01 Grande SÃ£o Paulo'),
  ('GUATAPARA', '13 RibeirÃ£o Preto'),
  ('GUZOLANDIA', '02 AraÃ§atuba'),
  ('HERCULANDIA', '09 MarÃ­lia'),
  ('HOLAMBRA', '07 Campinas'),
  ('HORTOLANDIA', '07 Campinas'),
  ('IACANGA', '06 Bauru'),
  ('IACRI', '09 MarÃ­lia'),
  ('IARAS', '06 Bauru'),
  ('IBATE', '03 Araraquara'),
  ('IBIRA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('IBIRAREMA', '09 MarÃ­lia'),
  ('IBITINGA', '03 Araraquara'),
  ('IBIUNA', '16 Sorocaba'),
  ('ICEM', '15 SÃ£o JosÃ© do Rio Preto'),
  ('IEPE', '11 Presidente Prudente'),
  ('IGARACU DO TIETE', '06 Bauru'),
  ('IGARAPAVA', '08 Franca'),
  ('IGARATA', '17 TaubatÃ©'),
  ('IGUAPE', '12 Registro'),
  ('ILHA BELA', '17 TaubatÃ©'),
  ('ILHA COMPRIDA', '12 Registro'),
  ('ILHA SOLTEIRA', '02 AraÃ§atuba'),
  ('INDAIATUBA', '07 Campinas'),
  ('INDIANA', '11 Presidente Prudente'),
  ('INDIAPORA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('INUBIA PAULISTA', '09 MarÃ­lia'),
  ('IPAUSSU', '09 MarÃ­lia'),
  ('IPERO', '16 Sorocaba'),
  ('IPEUNA', '10 Piracicaba'),
  ('IPIGUA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('IPORANGA', '12 Registro'),
  ('IPUA', '08 Franca'),
  ('IRACEMAPOLIS', '10 Piracicaba'),
  ('IRAPUA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('IRAPURU', '11 Presidente Prudente'),
  ('ITABERA', '16 Sorocaba'),
  ('ITAI', '06 Bauru'),
  ('ITAJOBI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ITAJU', '06 Bauru'),
  ('ITANHAEM', '04 Baixada Santista'),
  ('ITAOCA', '16 Sorocaba'),
  ('ITAPECERICA DA SERRA', '01 Grande SÃ£o Paulo'),
  ('ITAPETININGA', '16 Sorocaba'),
  ('ITAPEVA', '16 Sorocaba'),
  ('ITAPEVI', '01 Grande SÃ£o Paulo'),
  ('ITAPIRA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('ITAPIRAPUA PAULISTA', '16 Sorocaba'),
  ('ITAPOLIS', '03 Araraquara'),
  ('ITAPORANGA', '06 Bauru'),
  ('ITAPUI', '06 Bauru'),
  ('ITAPURA', '02 AraÃ§atuba'),
  ('ITAQUAQUECETUBA', '01 Grande SÃ£o Paulo'),
  ('ITARARE', '16 Sorocaba'),
  ('ITARIRI', '12 Registro'),
  ('ITATIBA', '07 Campinas'),
  ('ITATINGA', '06 Bauru'),
  ('ITIRAPINA', '10 Piracicaba'),
  ('ITIRAPUA', '08 Franca'),
  ('ITOBI', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('ITU', '16 Sorocaba'),
  ('ITUPEVA', '07 Campinas'),
  ('ITUVERAVA', '08 Franca'),
  ('JABORANDI', '05 Barretos'),
  ('JABOTICABAL', '13 RibeirÃ£o Preto'),
  ('JACAREI', '17 TaubatÃ©'),
  ('JACI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('JACUPIRANGA', '12 Registro'),
  ('JAGUARIUNA', '07 Campinas'),
  ('JALES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('JAMBEIRO', '17 TaubatÃ©'),
  ('JANDIRA', '01 Grande SÃ£o Paulo'),
  ('JARDINOPOLIS', '13 RibeirÃ£o Preto'),
  ('JARINU', '07 Campinas'),
  ('JAU', '06 Bauru'),
  ('JERIQUARA', '08 Franca'),
  ('JOANOPOLIS', '07 Campinas'),
  ('JOAO RAMALHO', '11 Presidente Prudente'),
  ('JOSE BONIFACIO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('JULIO MESQUITA', '09 MarÃ­lia'),
  ('JUMIRIM', '16 Sorocaba'),
  ('JUNDIAI', '07 Campinas'),
  ('JUNQUEIROPOLIS', '11 Presidente Prudente'),
  ('JUQUIA', '12 Registro'),
  ('JUQUITIBA', '01 Grande SÃ£o Paulo'),
  ('LAGOINHA', '17 TaubatÃ©'),
  ('LARANJAL PAULISTA', '06 Bauru'),
  ('LAVINIA', '02 AraÃ§atuba'),
  ('LAVRINHAS', '17 TaubatÃ©'),
  ('LEME', '10 Piracicaba'),
  ('LENCOIS PAULISTA', '06 Bauru'),
  ('LIMEIRA', '10 Piracicaba'),
  ('LINDOIA', '07 Campinas'),
  ('LINS', '06 Bauru'),
  ('LORENA', '17 TaubatÃ©'),
  ('LOURDES', '02 AraÃ§atuba'),
  ('LOUVEIRA', '07 Campinas'),
  ('LUCELIA', '09 MarÃ­lia'),
  ('LUCIANOPOLIS', '06 Bauru'),
  ('LUIS ANTONIO', '13 RibeirÃ£o Preto'),
  ('LUIZIANIA', '02 AraÃ§atuba'),
  ('LUPERCIO', '09 MarÃ­lia'),
  ('LUTECIA', '09 MarÃ­lia'),
  ('MACATUBA', '06 Bauru'),
  ('MACAUBAL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MACEDONIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MAGDA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MAIRINQUE', '16 Sorocaba'),
  ('MAIRIPORA', '01 Grande SÃ£o Paulo'),
  ('MANDURI', '06 Bauru'),
  ('MARABA PAULISTA', '11 Presidente Prudente'),
  ('MARACAI', '09 MarÃ­lia'),
  ('MARAPOAMA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MARIAPOLIS', '09 MarÃ­lia'),
  ('MARILIA', '09 MarÃ­lia'),
  ('MARINOPOLIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MARTINOPOLIS', '11 Presidente Prudente'),
  ('MATAO', '03 Araraquara'),
  ('MAUA', '01 Grande SÃ£o Paulo'),
  ('MENDONCA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MERIDIANO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MESOPOLIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MIGUELOPOLIS', '08 Franca'),
  ('MINEIROS DO TIETE', '06 Bauru'),
  ('MIRA ESTRELA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MIRACATU', '12 Registro'),
  ('MIRANDOPOLIS', '02 AraÃ§atuba'),
  ('MIRANTE DO PARANAPANEMA', '11 Presidente Prudente'),
  ('MIRASSOL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MIRASSOLANDIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MOCOCA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('MOGI DAS CRUZES', '01 Grande SÃ£o Paulo'),
  ('MOGI GUACU', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('MOGI MIRIM', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('MOMBUCA', '10 Piracicaba'),
  ('MONCOES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MONGAGUA', '04 Baixada Santista'),
  ('MONTE ALEGRE DO SUL', '07 Campinas'),
  ('MONTE ALTO', '13 RibeirÃ£o Preto'),
  ('MONTE APRAZIVEL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('MONTE AZUL PAULISTA', '05 Barretos'),
  ('MONTE CASTELO', '11 Presidente Prudente'),
  ('MONTE MOR', '07 Campinas'),
  ('MONTEIRO LOBATO', '17 TaubatÃ©'),
  ('MORRO AGUDO', '08 Franca'),
  ('MORUNGABA', '07 Campinas'),
  ('MOTUCA', '03 Araraquara'),
  ('MURUTINGA DO SUL', '02 AraÃ§atuba'),
  ('NANTES', '11 Presidente Prudente'),
  ('NARANDIBA', '11 Presidente Prudente'),
  ('NATIVIDADE DA SERRA', '17 TaubatÃ©'),
  ('NAZARE PAULISTA', '07 Campinas'),
  ('NEVES PAULISTA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NHANDEARA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NIPOA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NOVA ALIANCA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NOVA CAMPINA', '16 Sorocaba'),
  ('NOVA CANAA PAULISTA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NOVA CASTILHO', '02 AraÃ§atuba'),
  ('NOVA EUROPA', '03 Araraquara'),
  ('NOVA GRANADA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NOVA GUATAPORANGA', '11 Presidente Prudente'),
  ('NOVA INDEPENDENCIA', '02 AraÃ§atuba'),
  ('NOVA LUZITANIA', '02 AraÃ§atuba'),
  ('NOVA ODESSA', '07 Campinas'),
  ('NOVAIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NOVO HORIZONTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('NUPORANGA', '08 Franca'),
  ('OCAUCU', '09 MarÃ­lia'),
  ('OLEO', '09 MarÃ­lia'),
  ('OLIMPIA', '05 Barretos'),
  ('ONDA VERDE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ORIENTE', '09 MarÃ­lia'),
  ('ORINDIUVA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ORLANDIA', '08 Franca'),
  ('OSASCO', '01 Grande SÃ£o Paulo'),
  ('OSCAR BRESSANE', '09 MarÃ­lia'),
  ('OSVALDO CRUZ', '09 MarÃ­lia'),
  ('OURINHOS', '09 MarÃ­lia'),
  ('OURO VERDE', '11 Presidente Prudente'),
  ('OUROESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PACAEMBU', '09 MarÃ­lia'),
  ('PALESTINA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PALMARES PAULISTA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PALMEIRA D''OESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PALMITAL', '09 MarÃ­lia'),
  ('PANORAMA', '11 Presidente Prudente'),
  ('PARAGUACU PAULISTA', '09 MarÃ­lia'),
  ('PARAIBUNA', '17 TaubatÃ©'),
  ('PARAISO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PARANAPANEMA', '06 Bauru'),
  ('PARANAPUA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PARAPUA', '09 MarÃ­lia'),
  ('PARDINHO', '06 Bauru'),
  ('PARIQUERA-ACU', '12 Registro'),
  ('PARISI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PATROCINIO PAULISTA', '08 Franca'),
  ('PAULICEIA', '11 Presidente Prudente'),
  ('PAULINIA', '07 Campinas'),
  ('PAULISTANIA', '06 Bauru'),
  ('PAULO DE FARIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PEDERNEIRAS', '06 Bauru'),
  ('PEDRA BELA', '07 Campinas'),
  ('PEDRANOPOLIS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PEDREGULHO', '08 Franca'),
  ('PEDREIRA', '07 Campinas'),
  ('PEDRINHAS PAULISTA', '09 MarÃ­lia'),
  ('PEDRO DE TOLEDO', '12 Registro'),
  ('PENAPOLIS', '02 AraÃ§atuba'),
  ('PEREIRA BARRETO', '02 AraÃ§atuba'),
  ('PEREIRAS', '06 Bauru'),
  ('PERUIBE', '04 Baixada Santista'),
  ('PIACATU', '02 AraÃ§atuba'),
  ('PIEDADE', '16 Sorocaba'),
  ('PILAR DO SUL', '16 Sorocaba'),
  ('PINDAMONHANGABA', '17 TaubatÃ©'),
  ('PINDORAMA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PINHALZINHO', '07 Campinas'),
  ('PIQUEROBI', '11 Presidente Prudente'),
  ('PIQUETE', '17 TaubatÃ©'),
  ('PIRACAIA', '07 Campinas'),
  ('PIRACICABA', '10 Piracicaba'),
  ('PIRAJU', '06 Bauru'),
  ('PIRAJUI', '06 Bauru'),
  ('PIRANGI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PIRAPORA DO BOM JESUS', '01 Grande SÃ£o Paulo'),
  ('PIRAPOZINHO', '11 Presidente Prudente'),
  ('PIRASSUNUNGA', '10 Piracicaba'),
  ('PIRATININGA', '06 Bauru'),
  ('PITANGUEIRAS', '13 RibeirÃ£o Preto'),
  ('PLANALTO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PLATINA', '09 MarÃ­lia'),
  ('POA', '01 Grande SÃ£o Paulo'),
  ('POLONI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('POMPEIA', '09 MarÃ­lia'),
  ('PONGAI', '06 Bauru'),
  ('PONTAL', '13 RibeirÃ£o Preto'),
  ('PONTALINDA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PONTES GESTAL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('POPULINA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PORANGABA', '06 Bauru'),
  ('PORTO FELIZ', '16 Sorocaba'),
  ('PORTO FERREIRA', '03 Araraquara'),
  ('POTIM', '17 TaubatÃ©'),
  ('POTIRENDABA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('PRACINHA', '09 MarÃ­lia'),
  ('PRADOPOLIS', '13 RibeirÃ£o Preto'),
  ('PRAIA GRANDE', '04 Baixada Santista'),
  ('PRATANIA', '06 Bauru'),
  ('PRESIDENTE ALVES', '06 Bauru'),
  ('PRESIDENTE BERNARDES', '11 Presidente Prudente'),
  ('PRESIDENTE EPITACIO', '11 Presidente Prudente'),
  ('PRESIDENTE PRUDENTE', '11 Presidente Prudente'),
  ('PRESIDENTE VENCESLAU', '11 Presidente Prudente'),
  ('PROMISSAO', '06 Bauru'),
  ('QUADRA', '16 Sorocaba'),
  ('QUATA', '11 Presidente Prudente'),
  ('QUEIROZ', '09 MarÃ­lia'),
  ('QUELUZ', '17 TaubatÃ©'),
  ('QUINTANA', '09 MarÃ­lia'),
  ('RAFARD', '10 Piracicaba'),
  ('RANCHARIA', '11 Presidente Prudente'),
  ('REDENCAO DA SERRA', '17 TaubatÃ©'),
  ('REGENTE FEIJO', '11 Presidente Prudente'),
  ('REGINOPOLIS', '06 Bauru'),
  ('REGISTRO', '12 Registro'),
  ('RESTINGA', '08 Franca'),
  ('RIBEIRA', '16 Sorocaba'),
  ('RIBEIRAO BONITO', '03 Araraquara'),
  ('RIBEIRAO BRANCO', '16 Sorocaba'),
  ('RIBEIRAO CORRENTE', '08 Franca'),
  ('RIBEIRAO DO SUL', '09 MarÃ­lia'),
  ('RIBEIRAO DOS INDIOS', '11 Presidente Prudente'),
  ('RIBEIRAO GRANDE', '16 Sorocaba'),
  ('RIBEIRAO PIRES', '01 Grande SÃ£o Paulo'),
  ('RIBEIRAO PRETO', '13 RibeirÃ£o Preto'),
  ('RIFAINA', '08 Franca'),
  ('RINCAO', '03 Araraquara'),
  ('RINOPOLIS', '09 MarÃ­lia'),
  ('RIO CLARO', '10 Piracicaba'),
  ('RIO DAS PEDRAS', '10 Piracicaba'),
  ('RIO GRANDE DA SERRA', '01 Grande SÃ£o Paulo'),
  ('RIOLANDIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('RIVERSUL', '16 Sorocaba'),
  ('ROSANA', '11 Presidente Prudente'),
  ('ROSEIRA', '17 TaubatÃ©'),
  ('RUBIACEA', '02 AraÃ§atuba'),
  ('RUBINEIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SABINO', '06 Bauru'),
  ('SAGRES', '09 MarÃ­lia'),
  ('SALES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SALES OLIVEIRA', '08 Franca'),
  ('SALESOPOLIS', '01 Grande SÃ£o Paulo'),
  ('SALMOURAO', '09 MarÃ­lia'),
  ('SALTINHO', '10 Piracicaba'),
  ('SALTO', '16 Sorocaba'),
  ('SALTO DE PIRAPORA', '16 Sorocaba'),
  ('SALTO GRANDE', '09 MarÃ­lia'),
  ('SANDOVALINA', '11 Presidente Prudente'),
  ('SANTA ADELIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTA ALBERTINA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTA BARBARA D''OESTE', '07 Campinas'),
  ('SANTA BRANCA', '17 TaubatÃ©'),
  ('SANTA CLARA D''OESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTA CRUZ DA CONCEICAO', '10 Piracicaba'),
  ('SANTA CRUZ DA ESPERANCA', '13 RibeirÃ£o Preto'),
  ('SANTA CRUZ DAS PALMEIRAS', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('SANTA CRUZ DO RIO PARDO', '09 MarÃ­lia'),
  ('SANTA ERNESTINA', '03 Araraquara'),
  ('SANTA FE DO SUL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTA GERTRUDES', '10 Piracicaba'),
  ('SANTA ISABEL', '01 Grande SÃ£o Paulo'),
  ('SANTA LUCIA', '03 Araraquara'),
  ('SANTA MARIA DA SERRA', '10 Piracicaba'),
  ('SANTA MERCEDES', '11 Presidente Prudente'),
  ('SANTA RITA DO PASSA QUATRO', '13 RibeirÃ£o Preto'),
  ('SANTA RITA DOESTE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTA ROSA DE VITERBO', '13 RibeirÃ£o Preto'),
  ('SANTA SALETE', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTANA DA PONTE PENSA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SANTANA DE PARNAIBA', '01 Grande SÃ£o Paulo'),
  ('SANTO ANASTACIO', '11 Presidente Prudente'),
  ('SANTO ANDRE', '01 Grande SÃ£o Paulo'),
  ('SANTO ANTONIO DA ALEGRIA', '13 RibeirÃ£o Preto'),
  ('SANTO ANTONIO DA POSSE', '07 Campinas'),
  ('SANTO ANTONIO DO ARACANGUA', '02 AraÃ§atuba'),
  ('SANTO ANTONIO DO JARDIM', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('SANTO ANTONIO DO PINHAL', '17 TaubatÃ©'),
  ('SANTO EXPEDITO', '11 Presidente Prudente'),
  ('SANTOPOLIS DO AGUAPEI', '02 AraÃ§atuba'),
  ('SANTOS', '04 Baixada Santista'),
  ('SAO BENTO DO SAPUCAI', '17 TaubatÃ©'),
  ('SAO BERNARDO DO CAMPO', '01 Grande SÃ£o Paulo'),
  ('SAO CAETANO DO SUL', '01 Grande SÃ£o Paulo'),
  ('SAO CARLOS', '03 Araraquara'),
  ('SAO FRANCISCO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SAO JOAO DA BOA VISTA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('SAO JOAO DAS DUAS PONTES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SAO JOAO DE IRACEMA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SAO JOAO DO PAU D''ALHO', '11 Presidente Prudente'),
  ('SAO JOAQUIM DA BARRA', '08 Franca'),
  ('SAO JOSE DA BELA VISTA', '08 Franca'),
  ('SAO JOSE DO BARREIRO', '17 TaubatÃ©'),
  ('SAO JOSE DO RIO PARDO', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('SAO JOSE DO RIO PRETO', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SAO JOSE DOS CAMPOS', '17 TaubatÃ©'),
  ('SAO LOURENCO DA SERRA', '01 Grande SÃ£o Paulo'),
  ('SAO LUIZ DO PARAITINGA', '17 TaubatÃ©'),
  ('SAO MANUEL', '06 Bauru'),
  ('SAO MIGUEL ARCANJO', '16 Sorocaba'),
  ('SAO PAULO', '01 Grande SÃ£o Paulo'),
  ('SAO PEDRO', '10 Piracicaba'),
  ('SAO PEDRO DO TURVO', '09 MarÃ­lia'),
  ('SAO ROQUE', '16 Sorocaba'),
  ('SAO SEBASTIAO', '17 TaubatÃ©'),
  ('SAO SEBASTIAO DA GRAMA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('SAO SIMAO', '13 RibeirÃ£o Preto'),
  ('SAO VICENTE', '04 Baixada Santista'),
  ('SARAPUI', '16 Sorocaba'),
  ('SARUTAIA', '06 Bauru'),
  ('SEBASTIANOPOLIS DO SUL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('SERRA AZUL', '13 RibeirÃ£o Preto'),
  ('SERRA NEGRA', '07 Campinas'),
  ('SERRANA', '13 RibeirÃ£o Preto'),
  ('SERTAOZINHO', '13 RibeirÃ£o Preto'),
  ('SETE BARRAS', '12 Registro'),
  ('SEVERINIA', '05 Barretos'),
  ('SILVEIRAS', '17 TaubatÃ©'),
  ('SOCORRO', '07 Campinas'),
  ('SOROCABA', '16 Sorocaba'),
  ('SUD MENNUCCI', '02 AraÃ§atuba'),
  ('SUMARE', '07 Campinas'),
  ('SUZANAPOLIS', '02 AraÃ§atuba'),
  ('SUZANO', '01 Grande SÃ£o Paulo'),
  ('TABAPUA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('TABATINGA', '03 Araraquara'),
  ('TABOAO DA SERRA', '01 Grande SÃ£o Paulo'),
  ('TACIBA', '11 Presidente Prudente'),
  ('TAGUAI', '06 Bauru'),
  ('TAIACU', '05 Barretos'),
  ('TAIUVA', '05 Barretos'),
  ('TAMBAU', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('TANABI', '15 SÃ£o JosÃ© do Rio Preto'),
  ('TAPIRAI', '16 Sorocaba'),
  ('TAPIRATIBA', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('TAQUARAL', '05 Barretos'),
  ('TAQUARITINGA', '03 Araraquara'),
  ('TAQUARITUBA', '06 Bauru'),
  ('TAQUARIVAI', '16 Sorocaba'),
  ('TARABAI', '11 Presidente Prudente'),
  ('TARUMA', '09 MarÃ­lia'),
  ('TATUI', '16 Sorocaba'),
  ('TAUBATE', '17 TaubatÃ©'),
  ('TEJUPA', '06 Bauru'),
  ('TEODORO SAMPAIO', '11 Presidente Prudente'),
  ('TERRA ROXA', '05 Barretos'),
  ('TIETE', '16 Sorocaba'),
  ('TIMBURI', '09 MarÃ­lia'),
  ('TORRE DE PEDRA', '06 Bauru'),
  ('TORRINHA', '06 Bauru'),
  ('TRABIJU', '03 Araraquara'),
  ('TREMEMBE', '17 TaubatÃ©'),
  ('TRES FRONTEIRAS', '15 SÃ£o JosÃ© do Rio Preto'),
  ('TUIUTI', '07 Campinas'),
  ('TUPA', '09 MarÃ­lia'),
  ('TUPI PAULISTA', '11 Presidente Prudente'),
  ('TURIUBA', '02 AraÃ§atuba'),
  ('TURMALINA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('UBARANA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('UBATUBA', '17 TaubatÃ©'),
  ('UBIRAJARA', '09 MarÃ­lia'),
  ('UCHOA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('UNIAO PAULISTA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('URANIA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('URU', '06 Bauru'),
  ('URUPES', '15 SÃ£o JosÃ© do Rio Preto'),
  ('VALENTIM GENTIL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('VALINHOS', '07 Campinas'),
  ('VALPARAISO', '02 AraÃ§atuba'),
  ('VARGEM', '07 Campinas'),
  ('VARGEM GRANDE DO SUL', '14 SÃ£o JoÃ£o da Boa Vista'),
  ('VARGEM GRANDE PAULISTA', '01 Grande SÃ£o Paulo'),
  ('VARZEA PAULISTA', '07 Campinas'),
  ('VERA CRUZ', '09 MarÃ­lia'),
  ('VINHEDO', '07 Campinas'),
  ('VIRADOURO', '05 Barretos'),
  ('VISTA ALEGRE DO ALTO', '05 Barretos'),
  ('VITORIA BRASIL', '15 SÃ£o JosÃ© do Rio Preto'),
  ('VOTORANTIM', '16 Sorocaba'),
  ('VOTUPORANGA', '15 SÃ£o JosÃ© do Rio Preto'),
  ('ZACARIAS', '15 SÃ£o JosÃ© do Rio Preto')
ON CONFLICT (municipio) DO UPDATE SET drs = EXCLUDED.drs;

SELECT COUNT(*) AS total_drs FROM public.tab_drs;

-- â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tab_rras â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO public.tab_rras (municipio, rras) VALUES
  ('DIADEMA', 'RRAS 01'),
  ('MAUA', 'RRAS 01'),
  ('RIBEIRAO PIRES', 'RRAS 01'),
  ('RIO GRANDE DA SERRA', 'RRAS 01'),
  ('SANTO ANDRE', 'RRAS 01'),
  ('SAO BERNARDO DO CAMPO', 'RRAS 01'),
  ('SAO CAETANO DO SUL', 'RRAS 01'),
  ('ARUJA', 'RRAS 02'),
  ('BIRITIBA-MIRIM', 'RRAS 02'),
  ('FERRAZ DE VASCONCELOS', 'RRAS 02'),
  ('GUARAREMA', 'RRAS 02'),
  ('GUARULHOS', 'RRAS 02'),
  ('ITAQUAQUECETUBA', 'RRAS 02'),
  ('MOGI DAS CRUZES', 'RRAS 02'),
  ('POA', 'RRAS 02'),
  ('SALESOPOLIS', 'RRAS 02'),
  ('SANTA ISABEL', 'RRAS 02'),
  ('SUZANO', 'RRAS 02'),
  ('CAIEIRAS', 'RRAS 03'),
  ('CAJAMAR', 'RRAS 03'),
  ('FRANCISCO MORATO', 'RRAS 03'),
  ('FRANCO DA ROCHA', 'RRAS 03'),
  ('MAIRIPORA', 'RRAS 03'),
  ('COTIA', 'RRAS 04'),
  ('EMBU', 'RRAS 04'),
  ('EMBU-GUACU', 'RRAS 04'),
  ('ITAPECERICA DA SERRA', 'RRAS 04'),
  ('JUQUITIBA', 'RRAS 04'),
  ('SAO LOURENCO DA SERRA', 'RRAS 04'),
  ('TABOAO DA SERRA', 'RRAS 04'),
  ('VARGEM GRANDE PAULISTA', 'RRAS 04'),
  ('BARUERI', 'RRAS 05'),
  ('CARAPICUIBA', 'RRAS 05'),
  ('ITAPEVI', 'RRAS 05'),
  ('JANDIRA', 'RRAS 05'),
  ('OSASCO', 'RRAS 05'),
  ('PIRAPORA DO BOM JESUS', 'RRAS 05'),
  ('SANTANA DE PARNAIBA', 'RRAS 05'),
  ('SAO PAULO', 'RRAS 06'),
  ('BARRA DO TURVO', 'RRAS 07'),
  ('CAJATI', 'RRAS 07'),
  ('CANANEIA', 'RRAS 07'),
  ('ELDORADO', 'RRAS 07'),
  ('IGUAPE', 'RRAS 07'),
  ('ILHA COMPRIDA', 'RRAS 07'),
  ('IPORANGA', 'RRAS 07'),
  ('ITARIRI', 'RRAS 07'),
  ('JACUPIRANGA', 'RRAS 07'),
  ('JUQUIA', 'RRAS 07'),
  ('MIRACATU', 'RRAS 07'),
  ('PARIQUERA-ACU', 'RRAS 07'),
  ('PEDRO DE TOLEDO', 'RRAS 07'),
  ('REGISTRO', 'RRAS 07'),
  ('SETE BARRAS', 'RRAS 07'),
  ('BERTIOGA', 'RRAS 07'),
  ('CUBATAO', 'RRAS 07'),
  ('GUARUJA', 'RRAS 07'),
  ('ITANHAEM', 'RRAS 07'),
  ('MONGAGUA', 'RRAS 07'),
  ('PERUIBE', 'RRAS 07'),
  ('PRAIA GRANDE', 'RRAS 07'),
  ('SANTOS', 'RRAS 07'),
  ('SAO VICENTE', 'RRAS 07'),
  ('ALAMBARI', 'RRAS 08'),
  ('ANGATUBA', 'RRAS 08'),
  ('CAMPINA DO MONTE ALEGRE', 'RRAS 08'),
  ('CAPAO BONITO', 'RRAS 08'),
  ('CERQUILHO', 'RRAS 08'),
  ('CESARIO LANGE', 'RRAS 08'),
  ('GUAREI', 'RRAS 08'),
  ('ITAPETININGA', 'RRAS 08'),
  ('QUADRA', 'RRAS 08'),
  ('RIBEIRAO GRANDE', 'RRAS 08'),
  ('SAO MIGUEL ARCANJO', 'RRAS 08'),
  ('SARAPUI', 'RRAS 08'),
  ('TATUI', 'RRAS 08'),
  ('APIAI', 'RRAS 08'),
  ('BARRA DO CHAPEU', 'RRAS 08'),
  ('BOM SUCESSO DE ITARARE', 'RRAS 08'),
  ('BURI', 'RRAS 08'),
  ('GUAPIARA', 'RRAS 08'),
  ('ITABERA', 'RRAS 08'),
  ('ITAOCA', 'RRAS 08'),
  ('ITAPEVA', 'RRAS 08'),
  ('ITAPIRAPUA PAULISTA', 'RRAS 08'),
  ('ITARARE', 'RRAS 08'),
  ('NOVA CAMPINA', 'RRAS 08'),
  ('RIBEIRA', 'RRAS 08'),
  ('RIBEIRAO BRANCO', 'RRAS 08'),
  ('RIVERSUL', 'RRAS 08'),
  ('TAQUARIVAI', 'RRAS 08'),
  ('ALUMINIO', 'RRAS 08'),
  ('ARACARIGUAMA', 'RRAS 08'),
  ('ARACOIABA DA SERRA', 'RRAS 08'),
  ('BOITUVA', 'RRAS 08'),
  ('CAPELA DO ALTO', 'RRAS 08'),
  ('IBIUNA', 'RRAS 08'),
  ('IPERO', 'RRAS 08'),
  ('ITU', 'RRAS 08'),
  ('JUMIRIM', 'RRAS 08'),
  ('MAIRINQUE', 'RRAS 08'),
  ('PIEDADE', 'RRAS 08'),
  ('PILAR DO SUL', 'RRAS 08'),
  ('PORTO FELIZ', 'RRAS 08'),
  ('SALTO', 'RRAS 08'),
  ('SALTO DE PIRAPORA', 'RRAS 08'),
  ('SAO ROQUE', 'RRAS 08'),
  ('SOROCABA', 'RRAS 08'),
  ('TAPIRAI', 'RRAS 08'),
  ('TIETE', 'RRAS 08'),
  ('VOTORANTIM', 'RRAS 08'),
  ('AGUAS DE SANTA BARBARA', 'RRAS 09'),
  ('ARANDU', 'RRAS 09'),
  ('AVARE', 'RRAS 09'),
  ('BARAO DE ANTONINA', 'RRAS 09'),
  ('CERQUEIRA CESAR', 'RRAS 09'),
  ('CORONEL MACEDO', 'RRAS 09'),
  ('FARTURA', 'RRAS 09'),
  ('IARAS', 'RRAS 09'),
  ('ITAI', 'RRAS 09'),
  ('ITAPORANGA', 'RRAS 09'),
  ('MANDURI', 'RRAS 09'),
  ('PARANAPANEMA', 'RRAS 09'),
  ('PIRAJU', 'RRAS 09'),
  ('SARUTAIA', 'RRAS 09'),
  ('TAGUAI', 'RRAS 09'),
  ('TAQUARITUBA', 'RRAS 09'),
  ('TEJUPA', 'RRAS 09'),
  ('AGUDOS', 'RRAS 09'),
  ('AREALVA', 'RRAS 09'),
  ('AVAI', 'RRAS 09'),
  ('BALBINOS', 'RRAS 09'),
  ('BAURU', 'RRAS 09'),
  ('BOREBI', 'RRAS 09'),
  ('CABRALIA PAULISTA', 'RRAS 09'),
  ('DUARTINA', 'RRAS 09'),
  ('IACANGA', 'RRAS 09'),
  ('LENCOIS PAULISTA', 'RRAS 09'),
  ('LUCIANOPOLIS', 'RRAS 09'),
  ('MACATUBA', 'RRAS 09'),
  ('PAULISTANIA', 'RRAS 09'),
  ('PEDERNEIRAS', 'RRAS 09'),
  ('PIRAJUI', 'RRAS 09'),
  ('PIRATININGA', 'RRAS 09'),
  ('PRESIDENTE ALVES', 'RRAS 09'),
  ('REGINOPOLIS', 'RRAS 09'),
  ('ANHEMBI', 'RRAS 09'),
  ('AREIOPOLIS', 'RRAS 09'),
  ('BOFETE', 'RRAS 09'),
  ('BOTUCATU', 'RRAS 09'),
  ('CONCHAS', 'RRAS 09'),
  ('ITATINGA', 'RRAS 09'),
  ('LARANJAL PAULISTA', 'RRAS 09'),
  ('PARDINHO', 'RRAS 09'),
  ('PEREIRAS', 'RRAS 09'),
  ('PORANGABA', 'RRAS 09'),
  ('PRATANIA', 'RRAS 09'),
  ('SAO MANUEL', 'RRAS 09'),
  ('TORRE DE PEDRA', 'RRAS 09'),
  ('BARIRI', 'RRAS 09'),
  ('BARRA BONITA', 'RRAS 09'),
  ('BOCAINA', 'RRAS 09'),
  ('BORACEIA', 'RRAS 09'),
  ('BROTAS', 'RRAS 09'),
  ('DOIS CORREGOS', 'RRAS 09'),
  ('IGARACU DO TIETE', 'RRAS 09'),
  ('ITAJU', 'RRAS 09'),
  ('ITAPUI', 'RRAS 09'),
  ('JAU', 'RRAS 09'),
  ('MINEIROS DO TIETE', 'RRAS 09'),
  ('TORRINHA', 'RRAS 09'),
  ('CAFELANDIA', 'RRAS 09'),
  ('GETULINA', 'RRAS 09'),
  ('GUAICARA', 'RRAS 09'),
  ('LINS', 'RRAS 09'),
  ('PONGAI', 'RRAS 09'),
  ('PROMISSAO', 'RRAS 09'),
  ('SABINO', 'RRAS 09'),
  ('URU', 'RRAS 09'),
  ('ADAMANTINA', 'RRAS 10'),
  ('FLORIDA PAULISTA', 'RRAS 10'),
  ('INUBIA PAULISTA', 'RRAS 10'),
  ('LUCELIA', 'RRAS 10'),
  ('MARIAPOLIS', 'RRAS 10'),
  ('OSVALDO CRUZ', 'RRAS 10'),
  ('PACAEMBU', 'RRAS 10'),
  ('PRACINHA', 'RRAS 10'),
  ('SAGRES', 'RRAS 10'),
  ('SALMOURAO', 'RRAS 10'),
  ('ASSIS', 'RRAS 10'),
  ('BORA', 'RRAS 10'),
  ('CANDIDO MOTA', 'RRAS 10'),
  ('CRUZALIA', 'RRAS 10'),
  ('FLORINIA', 'RRAS 10'),
  ('IBIRAREMA', 'RRAS 10'),
  ('LUTECIA', 'RRAS 10'),
  ('MARACAI', 'RRAS 10'),
  ('PALMITAL', 'RRAS 10'),
  ('PARAGUACU PAULISTA', 'RRAS 10'),
  ('PEDRINHAS PAULISTA', 'RRAS 10'),
  ('PLATINA', 'RRAS 10'),
  ('TARUMA', 'RRAS 10'),
  ('ALVARO DE CARVALHO', 'RRAS 10'),
  ('ALVINLANDIA', 'RRAS 10'),
  ('CAMPOS NOVOS PAULISTA', 'RRAS 10'),
  ('ECHAPORA', 'RRAS 10'),
  ('FERNAO', 'RRAS 10'),
  ('GALIA', 'RRAS 10'),
  ('GARCA', 'RRAS 10'),
  ('GUAIMBE', 'RRAS 10'),
  ('GUARANTA', 'RRAS 10'),
  ('JULIO MESQUITA', 'RRAS 10'),
  ('LUPERCIO', 'RRAS 10'),
  ('MARILIA', 'RRAS 10'),
  ('OCAUCU', 'RRAS 10'),
  ('ORIENTE', 'RRAS 10'),
  ('OSCAR BRESSANE', 'RRAS 10'),
  ('POMPEIA', 'RRAS 10'),
  ('QUINTANA', 'RRAS 10'),
  ('UBIRAJARA', 'RRAS 10'),
  ('VERA CRUZ', 'RRAS 10'),
  ('BERNARDINO DE CAMPOS', 'RRAS 10'),
  ('CANITAR', 'RRAS 10'),
  ('CHAVANTES', 'RRAS 10'),
  ('ESPIRITO SANTO DO TURVO', 'RRAS 10'),
  ('IPAUSSU', 'RRAS 10'),
  ('OLEO', 'RRAS 10'),
  ('OURINHOS', 'RRAS 10'),
  ('RIBEIRAO DO SUL', 'RRAS 10'),
  ('SALTO GRANDE', 'RRAS 10'),
  ('SANTA CRUZ DO RIO PARDO', 'RRAS 10'),
  ('SAO PEDRO DO TURVO', 'RRAS 10'),
  ('TIMBURI', 'RRAS 10'),
  ('ARCO-IRIS', 'RRAS 10'),
  ('BASTOS', 'RRAS 10'),
  ('HERCULANDIA', 'RRAS 10'),
  ('IACRI', 'RRAS 10'),
  ('PARAPUA', 'RRAS 10'),
  ('QUEIROZ', 'RRAS 10'),
  ('RINOPOLIS', 'RRAS 10'),
  ('TUPA', 'RRAS 10'),
  ('DRACENA', 'RRAS 11'),
  ('FLORA RICA', 'RRAS 11'),
  ('IRAPURU', 'RRAS 11'),
  ('JUNQUEIROPOLIS', 'RRAS 11'),
  ('MONTE CASTELO', 'RRAS 11'),
  ('NOVA GUATAPORANGA', 'RRAS 11'),
  ('OURO VERDE', 'RRAS 11'),
  ('PANORAMA', 'RRAS 11'),
  ('PAULICEIA', 'RRAS 11'),
  ('SANTA MERCEDES', 'RRAS 11'),
  ('SAO JOAO DO PAU D''ALHO', 'RRAS 11'),
  ('TUPI PAULISTA', 'RRAS 11'),
  ('ALFREDO MARCONDES', 'RRAS 11'),
  ('ALVARES MACHADO', 'RRAS 11'),
  ('ANHUMAS', 'RRAS 11'),
  ('CAIABU', 'RRAS 11'),
  ('EMILIANOPOLIS', 'RRAS 11'),
  ('ESTRELA DO NORTE', 'RRAS 11'),
  ('INDIANA', 'RRAS 11'),
  ('MARTINOPOLIS', 'RRAS 11'),
  ('NARANDIBA', 'RRAS 11'),
  ('PIRAPOZINHO', 'RRAS 11'),
  ('PRESIDENTE BERNARDES', 'RRAS 11'),
  ('PRESIDENTE PRUDENTE', 'RRAS 11'),
  ('REGENTE FEIJO', 'RRAS 11'),
  ('RIBEIRAO DOS INDIOS', 'RRAS 11'),
  ('SANDOVALINA', 'RRAS 11'),
  ('SANTO ANASTACIO', 'RRAS 11'),
  ('SANTO EXPEDITO', 'RRAS 11'),
  ('TACIBA', 'RRAS 11'),
  ('TARABAI', 'RRAS 11'),
  ('IEPE', 'RRAS 11'),
  ('JOAO RAMALHO', 'RRAS 11'),
  ('NANTES', 'RRAS 11'),
  ('QUATA', 'RRAS 11'),
  ('RANCHARIA', 'RRAS 11'),
  ('CAIUA', 'RRAS 11'),
  ('MARABA PAULISTA', 'RRAS 11'),
  ('PIQUEROBI', 'RRAS 11'),
  ('PRESIDENTE EPITACIO', 'RRAS 11'),
  ('PRESIDENTE VENCESLAU', 'RRAS 11'),
  ('EUCLIDES DA CUNHA PAULISTA', 'RRAS 11'),
  ('MIRANTE DO PARANAPANEMA', 'RRAS 11'),
  ('ROSANA', 'RRAS 11'),
  ('TEODORO SAMPAIO', 'RRAS 11'),
  ('ARIRANHA', 'RRAS 12'),
  ('CATANDUVA', 'RRAS 12'),
  ('CATIGUA', 'RRAS 12'),
  ('ELISIARIO', 'RRAS 12'),
  ('EMBAUBA', 'RRAS 12'),
  ('FERNANDO PRESTES', 'RRAS 12'),
  ('IRAPUA', 'RRAS 12'),
  ('ITAJOBI', 'RRAS 12'),
  ('MARAPOAMA', 'RRAS 12'),
  ('NOVAIS', 'RRAS 12'),
  ('NOVO HORIZONTE', 'RRAS 12'),
  ('PALMARES PAULISTA', 'RRAS 12'),
  ('PARAISO', 'RRAS 12'),
  ('PINDORAMA', 'RRAS 12'),
  ('PIRANGI', 'RRAS 12'),
  ('SALES', 'RRAS 12'),
  ('SANTA ADELIA', 'RRAS 12'),
  ('TABAPUA', 'RRAS 12'),
  ('URUPES', 'RRAS 12'),
  ('NOVA CANAA PAULISTA', 'RRAS 12'),
  ('RUBINEIA', 'RRAS 12'),
  ('SANTA CLARA D''OESTE', 'RRAS 12'),
  ('SANTA FE DO SUL', 'RRAS 12'),
  ('SANTA RITA D''OESTE', 'RRAS 12'),
  ('TRES FRONTEIRAS', 'RRAS 12'),
  ('APARECIDA D''OESTE', 'RRAS 12'),
  ('ASPASIA', 'RRAS 12'),
  ('DIRCE REIS', 'RRAS 12'),
  ('DOLCINOPOLIS', 'RRAS 12'),
  ('JALES', 'RRAS 12'),
  ('MARINOPOLIS', 'RRAS 12'),
  ('MESOPOLIS', 'RRAS 12'),
  ('PALMEIRA D''OESTE', 'RRAS 12'),
  ('PARANAPUA', 'RRAS 12'),
  ('PONTALINDA', 'RRAS 12'),
  ('SANTA ALBERTINA', 'RRAS 12'),
  ('SANTA SALETE', 'RRAS 12'),
  ('SANTANA DA PONTE PENSA', 'RRAS 12'),
  ('SAO FRANCISCO', 'RRAS 12'),
  ('URANIA', 'RRAS 12'),
  ('VITORIA BRASIL', 'RRAS 12'),
  ('ESTRELA D''OESTE', 'RRAS 12'),
  ('FERNANDOPOLIS', 'RRAS 12'),
  ('GUARANI D''OESTE', 'RRAS 12'),
  ('INDIAPORA', 'RRAS 12'),
  ('MACEDONIA', 'RRAS 12'),
  ('MERIDIANO', 'RRAS 12'),
  ('MIRA ESTRELA', 'RRAS 12'),
  ('OUROESTE', 'RRAS 12'),
  ('PEDRANOPOLIS', 'RRAS 12'),
  ('POPULINA', 'RRAS 12'),
  ('SAO JOAO DAS DUAS PONTES', 'RRAS 12'),
  ('SAO JOAO DE IRACEMA', 'RRAS 12'),
  ('TURMALINA', 'RRAS 12'),
  ('BADY BASSITT', 'RRAS 12'),
  ('BALSAMO', 'RRAS 12'),
  ('CEDRAL', 'RRAS 12'),
  ('GUAPIACU', 'RRAS 12'),
  ('IBIRA', 'RRAS 12'),
  ('ICEM', 'RRAS 12'),
  ('IPIGUA', 'RRAS 12'),
  ('MIRASSOL', 'RRAS 12'),
  ('MIRASSOLANDIA', 'RRAS 12'),
  ('NEVES PAULISTA', 'RRAS 12'),
  ('NOVA ALIANCA', 'RRAS 12'),
  ('NOVA GRANADA', 'RRAS 12'),
  ('ONDA VERDE', 'RRAS 12'),
  ('ORINDIUVA', 'RRAS 12'),
  ('PALESTINA', 'RRAS 12'),
  ('PAULO DE FARIA', 'RRAS 12'),
  ('POTIRENDABA', 'RRAS 12'),
  ('SAO JOSE DO RIO PRETO', 'RRAS 12'),
  ('TANABI', 'RRAS 12'),
  ('UCHOA', 'RRAS 12'),
  ('ADOLFO', 'RRAS 12'),
  ('JACI', 'RRAS 12'),
  ('JOSE BONIFACIO', 'RRAS 12'),
  ('MENDONCA', 'RRAS 12'),
  ('MONTE APRAZIVEL', 'RRAS 12'),
  ('NIPOA', 'RRAS 12'),
  ('PLANALTO', 'RRAS 12'),
  ('POLONI', 'RRAS 12'),
  ('UBARANA', 'RRAS 12'),
  ('UNIAO PAULISTA', 'RRAS 12'),
  ('ZACARIAS', 'RRAS 12'),
  ('ALVARES FLORENCE', 'RRAS 12'),
  ('AMERICO DE CAMPOS', 'RRAS 12'),
  ('CARDOSO', 'RRAS 12'),
  ('COSMORAMA', 'RRAS 12'),
  ('FLOREAL', 'RRAS 12'),
  ('GASTAO VIDIGAL', 'RRAS 12'),
  ('GENERAL SALGADO', 'RRAS 12'),
  ('MACAUBAL', 'RRAS 12'),
  ('MAGDA', 'RRAS 12'),
  ('MONCOES', 'RRAS 12'),
  ('NHANDEARA', 'RRAS 12'),
  ('PARISI', 'RRAS 12'),
  ('PONTES GESTAL', 'RRAS 12'),
  ('RIOLANDIA', 'RRAS 12'),
  ('SEBASTIANOPOLIS DO SUL', 'RRAS 12'),
  ('VALENTIM GENTIL', 'RRAS 12'),
  ('VOTUPORANGA', 'RRAS 12'),
  ('ARACATUBA', 'RRAS 12'),
  ('AURIFLAMA', 'RRAS 12'),
  ('BENTO DE ABREU', 'RRAS 12'),
  ('BILAC', 'RRAS 12'),
  ('GUARARAPES', 'RRAS 12'),
  ('GUZOLANDIA', 'RRAS 12'),
  ('NOVA CASTILHO', 'RRAS 12'),
  ('NOVA LUZITANIA', 'RRAS 12'),
  ('RUBIACEA', 'RRAS 12'),
  ('SANTO ANTONIO DO ARACANGUA', 'RRAS 12'),
  ('VALPARAISO', 'RRAS 12'),
  ('ANDRADINA', 'RRAS 12'),
  ('CASTILHO', 'RRAS 12'),
  ('GUARACAI', 'RRAS 12'),
  ('ILHA SOLTEIRA', 'RRAS 12'),
  ('ITAPURA', 'RRAS 12'),
  ('LAVINIA', 'RRAS 12'),
  ('MIRANDOPOLIS', 'RRAS 12'),
  ('MURUTINGA DO SUL', 'RRAS 12'),
  ('NOVA INDEPENDENCIA', 'RRAS 12'),
  ('PEREIRA BARRETO', 'RRAS 12'),
  ('SUD MENNUCCI', 'RRAS 12'),
  ('SUZANAPOLIS', 'RRAS 12'),
  ('ALTO ALEGRE', 'RRAS 12'),
  ('AVANHANDAVA', 'RRAS 12'),
  ('BARBOSA', 'RRAS 12'),
  ('BIRIGUI', 'RRAS 12'),
  ('BRAUNA', 'RRAS 12'),
  ('BREJO ALEGRE', 'RRAS 12'),
  ('BURITAMA', 'RRAS 12'),
  ('CLEMENTINA', 'RRAS 12'),
  ('COROADOS', 'RRAS 12'),
  ('GABRIEL MONTEIRO', 'RRAS 12'),
  ('GLICERIO', 'RRAS 12'),
  ('LOURDES', 'RRAS 12'),
  ('LUIZIANIA', 'RRAS 12'),
  ('PENAPOLIS', 'RRAS 12'),
  ('PIACATU', 'RRAS 12'),
  ('SANTOPOLIS DO AGUAPEI', 'RRAS 12'),
  ('TURIUBA', 'RRAS 12'),
  ('BARRINHA', 'RRAS 13'),
  ('DUMONT', 'RRAS 13'),
  ('GUARIBA', 'RRAS 13'),
  ('JABOTICABAL', 'RRAS 13'),
  ('MONTE ALTO', 'RRAS 13'),
  ('PITANGUEIRAS', 'RRAS 13'),
  ('PONTAL', 'RRAS 13'),
  ('PRADOPOLIS', 'RRAS 13'),
  ('SERTAOZINHO', 'RRAS 13'),
  ('CRAVINHOS', 'RRAS 13'),
  ('GUATAPARA', 'RRAS 13'),
  ('JARDINOPOLIS', 'RRAS 13'),
  ('LUIS ANTONIO', 'RRAS 13'),
  ('RIBEIRAO PRETO', 'RRAS 13'),
  ('SANTA RITA DO PASSA QUATRO', 'RRAS 13'),
  ('SANTA ROSA DE VITERBO', 'RRAS 13'),
  ('SAO SIMAO', 'RRAS 13'),
  ('SERRA AZUL', 'RRAS 13'),
  ('SERRANA', 'RRAS 13'),
  ('ALTINOPOLIS', 'RRAS 13'),
  ('BATATAIS', 'RRAS 13'),
  ('BRODOWSKI', 'RRAS 13'),
  ('CAJURU', 'RRAS 13'),
  ('CASSIA DOS COQUEIROS', 'RRAS 13'),
  ('SANTA CRUZ DA ESPERANCA', 'RRAS 13'),
  ('SANTO ANTONIO DA ALEGRIA', 'RRAS 13'),
  ('AMERICO BRASILIENSE', 'RRAS 13'),
  ('ARARAQUARA', 'RRAS 13'),
  ('BOA ESPERANCA DO SUL', 'RRAS 13'),
  ('GAVIAO PEIXOTO', 'RRAS 13'),
  ('MOTUCA', 'RRAS 13'),
  ('RINCAO', 'RRAS 13'),
  ('SANTA LUCIA', 'RRAS 13'),
  ('TRABIJU', 'RRAS 13'),
  ('BORBOREMA', 'RRAS 13'),
  ('IBITINGA', 'RRAS 13'),
  ('ITAPOLIS', 'RRAS 13'),
  ('NOVA EUROPA', 'RRAS 13'),
  ('TABATINGA', 'RRAS 13'),
  ('CANDIDO RODRIGUES', 'RRAS 13'),
  ('DOBRADA', 'RRAS 13'),
  ('MATAO', 'RRAS 13'),
  ('SANTA ERNESTINA', 'RRAS 13'),
  ('TAQUARITINGA', 'RRAS 13'),
  ('DESCALVADO', 'RRAS 13'),
  ('DOURADO', 'RRAS 13'),
  ('IBATE', 'RRAS 13'),
  ('PORTO FERREIRA', 'RRAS 13'),
  ('RIBEIRAO BONITO', 'RRAS 13'),
  ('SAO CARLOS', 'RRAS 13'),
  ('ALTAIR', 'RRAS 13'),
  ('BARRETOS', 'RRAS 13'),
  ('CAJOBI', 'RRAS 13'),
  ('COLINA', 'RRAS 13'),
  ('COLOMBIA', 'RRAS 13'),
  ('GUAIRA', 'RRAS 13'),
  ('GUARACI', 'RRAS 13'),
  ('JABORANDI', 'RRAS 13'),
  ('OLIMPIA', 'RRAS 13'),
  ('SEVERINIA', 'RRAS 13'),
  ('BEBEDOURO', 'RRAS 13'),
  ('MONTE AZUL PAULISTA', 'RRAS 13'),
  ('TAIACU', 'RRAS 13'),
  ('TAIUVA', 'RRAS 13'),
  ('TAQUARAL', 'RRAS 13'),
  ('TERRA ROXA', 'RRAS 13'),
  ('VIRADOURO', 'RRAS 13'),
  ('VISTA ALEGRE DO ALTO', 'RRAS 13'),
  ('CRISTAIS PAULISTA', 'RRAS 13'),
  ('FRANCA', 'RRAS 13'),
  ('ITIRAPUA', 'RRAS 13'),
  ('JERIQUARA', 'RRAS 13'),
  ('PATROCINIO PAULISTA', 'RRAS 13'),
  ('PEDREGULHO', 'RRAS 13'),
  ('RESTINGA', 'RRAS 13'),
  ('RIBEIRAO CORRENTE', 'RRAS 13'),
  ('RIFAINA', 'RRAS 13'),
  ('SAO JOSE DA BELA VISTA', 'RRAS 13'),
  ('IPUA', 'RRAS 13'),
  ('MORRO AGUDO', 'RRAS 13'),
  ('NUPORANGA', 'RRAS 13'),
  ('ORLANDIA', 'RRAS 13'),
  ('SALES OLIVEIRA', 'RRAS 13'),
  ('SAO JOAQUIM DA BARRA', 'RRAS 13'),
  ('ARAMINA', 'RRAS 13'),
  ('BURITIZAL', 'RRAS 13'),
  ('GUARA', 'RRAS 13'),
  ('IGARAPAVA', 'RRAS 13'),
  ('ITUVERAVA', 'RRAS 13'),
  ('MIGUELOPOLIS', 'RRAS 13'),
  ('ARARAS', 'RRAS 14'),
  ('CONCHAL', 'RRAS 14'),
  ('LEME', 'RRAS 14'),
  ('PIRASSUNUNGA', 'RRAS 14'),
  ('SANTA CRUZ DA CONCEICAO', 'RRAS 14'),
  ('CORDEIROPOLIS', 'RRAS 14'),
  ('ENGENHEIRO COELHO', 'RRAS 14'),
  ('IRACEMAPOLIS', 'RRAS 14'),
  ('LIMEIRA', 'RRAS 14'),
  ('AGUAS DE SAO PEDRO', 'RRAS 14'),
  ('CAPIVARI', 'RRAS 14'),
  ('CHARQUEADA', 'RRAS 14'),
  ('ELIAS FAUSTO', 'RRAS 14'),
  ('MOMBUCA', 'RRAS 14'),
  ('PIRACICABA', 'RRAS 14'),
  ('RAFARD', 'RRAS 14'),
  ('RIO DAS PEDRAS', 'RRAS 14'),
  ('SALTINHO', 'RRAS 14'),
  ('SANTA MARIA DA SERRA', 'RRAS 14'),
  ('SAO PEDRO', 'RRAS 14'),
  ('ANALANDIA', 'RRAS 14'),
  ('CORUMBATAI', 'RRAS 14'),
  ('IPEUNA', 'RRAS 14'),
  ('ITIRAPINA', 'RRAS 14'),
  ('RIO CLARO', 'RRAS 14'),
  ('SANTA GERTRUDES', 'RRAS 14'),
  ('ESTIVA GERBI', 'RRAS 15'),
  ('ITAPIRA', 'RRAS 15'),
  ('MOGI GUACU', 'RRAS 15'),
  ('MOGI MIRIM', 'RRAS 15'),
  ('AGUAI', 'RRAS 15'),
  ('AGUAS DA PRATA', 'RRAS 15'),
  ('ESPIRITO SANTO DO PINHAL', 'RRAS 15'),
  ('SANTA CRUZ DAS PALMEIRAS', 'RRAS 15'),
  ('SANTO ANTONIO DO JARDIM', 'RRAS 15'),
  ('SAO JOAO DA BOA VISTA', 'RRAS 15'),
  ('TAMBAU', 'RRAS 15'),
  ('VARGEM GRANDE DO SUL', 'RRAS 15'),
  ('CACONDE', 'RRAS 15'),
  ('CASA BRANCA', 'RRAS 15'),
  ('DIVINOLANDIA', 'RRAS 15'),
  ('ITOBI', 'RRAS 15'),
  ('MOCOCA', 'RRAS 15'),
  ('SAO JOSE DO RIO PARDO', 'RRAS 15'),
  ('SAO SEBASTIAO DA GRAMA', 'RRAS 15'),
  ('TAPIRATIBA', 'RRAS 15'),
  ('AGUAS DE LINDOIA', 'RRAS 16'),
  ('AMPARO', 'RRAS 16'),
  ('CAMPINAS', 'RRAS 16'),
  ('INDAIATUBA', 'RRAS 16'),
  ('LINDOIA', 'RRAS 16'),
  ('MONTE ALEGRE DO SUL', 'RRAS 16'),
  ('MONTE MOR', 'RRAS 16'),
  ('PEDREIRA', 'RRAS 16'),
  ('SERRA NEGRA', 'RRAS 16'),
  ('VALINHOS', 'RRAS 16'),
  ('VINHEDO', 'RRAS 16'),
  ('AMERICANA', 'RRAS 16'),
  ('ARTUR NOGUEIRA', 'RRAS 16'),
  ('COSMOPOLIS', 'RRAS 16'),
  ('HOLAMBRA', 'RRAS 16'),
  ('HORTOLANDIA', 'RRAS 16'),
  ('JAGUARIUNA', 'RRAS 16'),
  ('NOVA ODESSA', 'RRAS 16'),
  ('PAULINIA', 'RRAS 16'),
  ('SANTA BARBARA D''OESTE', 'RRAS 16'),
  ('SANTO ANTONIO DE POSSE', 'RRAS 16'),
  ('SUMARE', 'RRAS 16'),
  ('ATIBAIA', 'RRAS 16'),
  ('BOM JESUS DOS PERDOES', 'RRAS 16'),
  ('BRAGANCA PAULISTA', 'RRAS 16'),
  ('JOANOPOLIS', 'RRAS 16'),
  ('NAZARE PAULISTA', 'RRAS 16'),
  ('PEDRA BELA', 'RRAS 16'),
  ('PINHALZINHO', 'RRAS 16'),
  ('PIRACAIA', 'RRAS 16'),
  ('SOCORRO', 'RRAS 16'),
  ('TUIUTI', 'RRAS 16'),
  ('VARGEM', 'RRAS 16'),
  ('CABREUVA', 'RRAS 16'),
  ('CAMPO LIMPO PAULISTA', 'RRAS 16'),
  ('ITATIBA', 'RRAS 16'),
  ('ITUPEVA', 'RRAS 16'),
  ('JARINU', 'RRAS 16'),
  ('JUNDIAI', 'RRAS 16'),
  ('LOUVEIRA', 'RRAS 16'),
  ('MORUNGABA', 'RRAS 16'),
  ('VARZEA PAULISTA', 'RRAS 16'),
  ('CACAPAVA', 'RRAS 17'),
  ('IGARATA', 'RRAS 17'),
  ('JACAREI', 'RRAS 17'),
  ('JAMBEIRO', 'RRAS 17'),
  ('MONTEIRO LOBATO', 'RRAS 17'),
  ('PARAIBUNA', 'RRAS 17'),
  ('SANTA BRANCA', 'RRAS 17'),
  ('SAO JOSE DOS CAMPOS', 'RRAS 17'),
  ('APARECIDA', 'RRAS 17'),
  ('ARAPEI', 'RRAS 17'),
  ('AREIAS', 'RRAS 17'),
  ('BANANAL', 'RRAS 17'),
  ('CACHOEIRA PAULISTA', 'RRAS 17'),
  ('CANAS', 'RRAS 17'),
  ('CRUZEIRO', 'RRAS 17'),
  ('CUNHA', 'RRAS 17'),
  ('GUARATINGUETA', 'RRAS 17'),
  ('LAVRINHAS', 'RRAS 17'),
  ('LORENA', 'RRAS 17'),
  ('PIQUETE', 'RRAS 17'),
  ('POTIM', 'RRAS 17'),
  ('QUELUZ', 'RRAS 17'),
  ('ROSEIRA', 'RRAS 17'),
  ('SAO JOSE DO BARREIRO', 'RRAS 17'),
  ('SILVEIRAS', 'RRAS 17'),
  ('CARAGUATATUBA', 'RRAS 17'),
  ('ILHABELA', 'RRAS 17'),
  ('SAO SEBASTIAO', 'RRAS 17'),
  ('UBATUBA', 'RRAS 17'),
  ('CAMPOS DO JORDAO', 'RRAS 17'),
  ('LAGOINHA', 'RRAS 17'),
  ('NATIVIDADE DA SERRA', 'RRAS 17'),
  ('PINDAMONHANGABA', 'RRAS 17'),
  ('REDENCAO DA SERRA', 'RRAS 17'),
  ('SANTO ANTONIO DO PINHAL', 'RRAS 17'),
  ('SAO BENTO DO SAPUCAI', 'RRAS 17'),
  ('SAO LUIS DO PARAITINGA', 'RRAS 17'),
  ('TAUBATE', 'RRAS 17'),
  ('TREMEMBE', 'RRAS 17')
ON CONFLICT (municipio) DO UPDATE SET rras = EXCLUDED.rras;

SELECT COUNT(*) AS total_rras FROM public.tab_rras;
